---
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost                # Chose the desired installation name. Example = mm-example-full
spec:
  size: 100users                       # Adjust to your requirements. Example = 5000users
  ingress:
    enabled: true
    host: ${MATTERMOST_HOST}               # Adjust to your domain. Example = example.mattermost-example.com
    annotations:
      kubernetes.io/ingress.class: nginx
  version: ${MATTERMOST_VERSION}                       # Select a recent supported version of Mattermost. Example = 9.3.0
  licenseSecret: mattermost-license                             # If you created a license secret in step 1, put the secret name here
  mattermostEnv:
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "true"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "true"
  fileStore:
    external:
      url: ${MINIO_S3_HOST} # Adjust to your MinIO service URL. Example = http://minio.example.com:9000
      bucket: ${MINIO_BUCKET}
      secret: s3-credentials-mattermost
  database:
    external:
      secret: postgresql-credentials-mattermost
